### PR TITLE
16.0.0 release

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
Changelog entry added and version changed to 16.0.0 in several places

### CODE REVIEW

**Comment by psi29a** [comment]
It is done, I'll upload to pypi in a few.

**Comment by trenton42** [comment]
:tada: :clap: Thanks @IlyaSkriblovsky @psi29a!

**Comment by psi29a** [comment]
Done: https://pypi.python.org/pypi/txmongo/16.0.0

**Comment by fiorix** [comment]
Good job, guys. Happy to see this thing moving forward.

**Pull request merged**
