### PR TITLE
add create_collection coverage

### PR DESCRIPTION
**Pull request by psi29a**
drop collection via database

cover drop collection typeerror

### CODE REVIEW

**Comment by psi29a** [comment]
We just broke 80% coverage! :)

**Comment by trenton42** [comment]
@psi29a Way to go! I really appreciate everything you all are doing here!

**Comment by psi29a** [comment]
Give a big thanks to @IlyaSkriblovsky as he has been really on the ball.  :)

**Comment by IlyaSkriblovsky** [comment]
Cool!

I've looked into sporadically failed tests and found that this happens for tests that create `MongoConnection` and immediately call its `disconnect()` without issuing any queries. `MongoConnection()` constructor starts connecting in background. Connection process in turn starts name resolution of "localhost" into ip-address. If name resolution doesn't finish until `disconnect()` returns (it takes exactly 1 main loop round-trip), trial fails with "reactor unclean". (Name resolution is deferred to separate thread, so there is race condition which fails more often on slow machines).

Unfortunately, I didn't found any good way to wait until name resolution is done :(

The simpliest way to solve this is to change "localhost" to "127.0.0.1" in `test_queries.py` and `test_aggregate.py`. Or to issue any command on `MongoConnection` in corresponding test methods.

**Pull request merged**
