### PR TITLE
we cannot guarentee the order of a list, so we make sure all elements…

### PR DESCRIPTION
**Pull request by psi29a**
… are find in a list

This is to fix this from happening:
https://travis-ci.org/psi29a/txmongo/jobs/62363503

### CODE REVIEW

**Comment by psi29a** [comment]
@IlyaSkriblovsky you agree with this fix?

**Comment by IlyaSkriblovsky** [comment]
Sure, it's good to go

**Comment by psi29a** [comment]
I added support for the latest official mongodb from their ubuntu archives... currently that is version 2.6.9
I don't know when 3.0.x will go in, hopefully soon.

**Comment by psi29a** [comment]
Travis seems to be happy now, the only failing test I see is about the orderedict.

**Pull request merged**
