### PR TITLE
kwargs removed where it is not necessary

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
removed `kwargs` where it is not necessary and made `@timeout`'s `_deadline` argument explicit in most cases

### CODE REVIEW

**Comment by psi29a** [comment]
:+1:  Yes, less kwarg magic... thanks you

**Comment by psi29a** [comment]
```
txmongo/collection.py:26: 'txmongo.protocol.INSERT_CONTINUE_ON_ERROR' imported but unused
```
hmmm

**Comment by IlyaSkriblovsky** [comment]
Thanks, removed that unused import. It became unused after simplifying internal function that was before used for both `insert _one` and `insert _many` but now serves only `insert _one`.

**Comment by psi29a** [comment]
merging!  :D

**Pull request merged**
