### PR TITLE
Circular reference removed between after_reply and its closures

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
I was investigating how my server consumes RAM and noticed that each call to `find()` or `find_one()` creates unreachable reference cycle and this is (among with other reasons) why my app is constantly triggers GC.

`after_reply` inside `find_with_cursor` does some sort of deferred recursion and so references itself. This creates unobvious reference cycle between function object of `after_reply` and its closure.

Proposed solution is to break self-reference of `after_reply` by passing this reference into function via arguments. Rather tricky though, but less intrusive than moving `after_reference` to outer scope to remove closure.

Testing code:
```python
gc.disable()
print(len(gc.get_objects()))
for i in range(10000):
    yield coll.find_one()
print(len(gc.get_objects()))
```

Before:
```
19813
89630
```

After:
```
19796
19611
```

Since the default GC threshold is 700, "before" version triggers GC pretty often.

### CODE REVIEW

**Comment by psi29a** [comment]
Great find!

**Comment by IlyaSkriblovsky** [comment]
Yes, in pythonic meaning of the term. GC will be able to clean this of course, but it's better to not summon it without a need. 10k of `find_one` was triggering GC ~80 times, with this fix it doesn't at all.

**Comment by trenton42** [comment]
Wow, that is a great find! I have been puzzling over memory usage for quite a while, but I never got anywhere with it.

Any Idea when the next pypi release will be?

**Comment by IlyaSkriblovsky** [comment]
@psi29a, do you think this fix deserves a minor release? I can fill the changelog if so

**Comment by psi29a** [comment]
I believe it does, yes. Please do.  I'm in the middle of a release here at work so this is perfect timing.

We should make this 16.0, since it is 2016 now and well... memory 'leaks' are rather important. ;)

**Comment by IlyaSkriblovsky** [comment]
Opened #141 for 16.0.0

**Pull request merged**
