### PR TITLE
X509 auth

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
Rebased #176 onto master and added the simple testcase

### CODE REVIEW

**Comment by psi29a** [comment]
Looks great, we'll take it. :)

**Comment by psi29a** [comment]
Before merge, can a changelog entry be added?

**Comment by IlyaSkriblovsky** [comment]
Sorry, I'm always forgetting about changelog...

**Comment by psi29a** [comment]
Conflict with previously MR, sorry!

**Comment by IlyaSkriblovsky** [comment]
Changelog entries were conflicting :)

Rebased

**Comment by psi29a** [comment]
Done and done, thanks! :)

**Pull request merged**
