### PR TITLE
Collection.bulk_write()

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
Implementation of PyMongo's `Collection.bulk_write()` method.

Some internals of PyMongo used to avoid copy-pasting.

### CODE REVIEW

**Comment by psi29a** [comment]
Well that was fast. ;)

**Comment by psi29a** [comment]
LGTM :+1: 

Can you update the changelog/news file please?

This is worthy of a 16.2 release ;)

**Comment by IlyaSkriblovsky** [comment]
Updated NEWS.rst. Sorry, I'm always forgetting about that.

I think we should handle watchdog issue before 16.2.0... At least increase default timeouts as suggested in #171.

**Comment by psi29a** [comment]
Done, thanks! :)

**Pull request merged**
