### PR TITLE
18.0.0

### PR DESCRIPTION
**Pull request by IlyaSkriblovsky**
I wish changelog for this release to be longer, but this single lonely line looks serious enough

### CODE REVIEW

**Comment by psi29a** [comment]
Serious release, sometimes one line-item is enough. :)

**Comment by IlyaSkriblovsky** [comment]
Could you please upload it to PyPI?

**Comment by psi29a** [comment]
Already done! :D

**Comment by IlyaSkriblovsky** [comment]
@psi29a Thanks!

**Pull request merged**
