### PR TITLE
Refactor: add black and isort

### PR DESCRIPTION
**Pull request by NikolayBaranovv**
merge after #291

### CODE REVIEW

**Review by IlyaSkriblovsky — APPROVED** [review]

**Comment by NikolayBaranovv** [comment]
@psi29a all done!

**Comment by psi29a** [comment]
Screenshot 2024-10-01 at 09 43 13
Oef, needs another go?

**Comment by NikolayBaranovv** [comment]
> Screenshot 2024-10-01 at 09 43 13 Oef, needs another go?

Yep, simple rebase :smile:

**Comment by psi29a** [comment]
Screenshot 2024-10-01 at 11 52 05

Simple? 🙈

**Comment by NikolayBaranovv** [comment]
> Simple? 🙈

Yep. no conflicts when rebase :smiley: 
 
> black is really opinionated


It's easy to get used to it :laughing:

**Pull request merged**
